### ISSUE TITLE
Choose the right parser automatically based on the meta data stored in .zim file

### ISSUE THREAD

**Issue by elfxiong** [elfxiong/wiktionary-translations-parser#2]
Zim file's meta data contains language information. It is a three-letter code (not sure if it is `ISO639-3` or `ISO6392`), while Wiktionary uses `ISO639-1`, `ISO639-3` and then `other standards`, in this order. 
We can either index out parsers based on the same code Wiktionary uses, or based on `ISO639-3`. The former one makes more sense to me - since we're making parses for Wiktionary, being consistent with its notation is more straightforward. Either way we need to convert between language codes.

**Comment by aaronmueller** [comment]
We could possibly add a column to our Wiktionary information spreadsheet that has the Wiktionary and the ISO639-3 language codes. That way, we can just use that information to convert easily between language codes as necessary. 

Otherwise, I would recommend sticking with the Wiktionary codes because they are more consistent with the medium we're using to extract our information (plus we already have them).

**Comment by elfxiong** [comment]
According to http://www.openzim.org/wiki/Metadata, the `Language` in .zim metadata is using `ISO639-3` standard language code. It also says there can be multiple languages (separated by comma).
I'm also thinking about using `Source` (URI of the original source) to get the Wiktionary code. But `Source` is an optional field though.

I don't think to we need to add the language code to the spreadsheet manually, since there are Python packages that converts the language codes. `pycountry` and `iso-639` are two packages that can be used for converting between language codes. `iso-639`'s data is a little bit outdated because I wasn't able to find some codes when I used it in the past.

**Comment by elfxiong** [comment]
Printing out the metadata from a .zim I'm using to test the ja edition parser, I get

> language : jpn
> date : 2016-05-19
> creator : Wiktionary
> title : Wiktionary
> counter : application/javascript=3;image/gif=4;image/png=109;image/svg+xml=15;text/css=1;text/html=152374;text/plain=7;
> publisher : Kiwix
> description : 出典: フリー多機能辞典『ウィクショナリー日本語版（Wiktionary）』

So there is no URI. I think I'm going to grab the `jpn`, which is in `ISO639-3`, and convert it to Wiktionary code and print out both codes in the output .csv.
